import { Injectable } from "@nestjs/common";
import type { AgentInput, AgentOutput } from "../../common/types/agent.types";
import type { AgentAdapter } from "./agent-adapter.interface";

@Injectable()
export class MockAgentAdapter implements AgentAdapter {
  async generate(input: AgentInput): Promise<AgentOutput> {
    const contentByRole: Record<string, string> = {
      orchestrator: "已完成任务拆解：产品结构 -> 视觉方案 -> 前端代码 -> 代码审查 -> Artifact 聚合。",
      product: "建议单页结构：Hero、项目精选、技能矩阵、联系方式，确保 Demo 讲解路径清晰。",
      design: "视觉方向：深色开发工具感，使用高对比文字、蓝色操作色和绿色状态色，右侧保留实时预览。",
      frontend: "已生成 HTML Artifact，可在右侧 Preview 中展示，并可继续通过 Diff 修改。",
      review: "代码审查建议：补充响应式断点、减少内联样式、确认 iframe sandbox 策略。",
    };

    return {
      agentId: input.agent.id,
      content: contentByRole[input.agent.role] ?? `Mock response for ${input.task}`,
      artifacts:
        input.agent.role === "frontend"
          ? [
              {
                type: "html",
                title: "portfolio.html",
                content: "<main><h1>AI Portfolio</h1><p>Generated by AgentHub Studio.</p></main>",
              },
            ]
          : undefined,
    };
  }
}

